LGBMRegressor:
  boosting_type: "gbdt"
  num_leaves: 31
  max_depth: 15
  # num_leaves:  2**(max_depth)//8 # must be at most 2^max_depth 
  learning_rate: 1e-1
  n_estimators: 200
  subsample_for_bin: 200000
  objective: "mse" # To be updated inside of custom models
  class_weight: null
  min_child_samples: 30
  colsample_bytree: 1.0
  reg_alpha: 1e-3
  reg_lambda: 1e-2
  random_state : 2025
  n_jobs: 1
  importance_type: "split"
  # verbose:-2,
  # verbosity:-2,
  # verbose_eval:False,
  # verbosity_eval:False,
