#!/usr/bin/env python3
"""Generate FINAL_EVIDENCE_INDEX.md and MANUSCRIPT_REVISION_SPEC.md.

Both documents are DERIVED from the maps and specs rather than hand-written, so
they cannot drift out of sync with the evidence. Regenerate after any change to
spec/*.yaml or to the maps.

FINAL_EVIDENCE_INDEX.md is organised by manuscript section, then by evidence
domain, and it walks the mandated coverage topics one for one.

MANUSCRIPT_REVISION_SPEC.md is organised as the writing pass will work: by
priority, then by section, with the three cross-cutting sections -- todo
closure, literature and novelty boundary, and document integrity -- plus the
mandatory table highlighting and labelling convention that feedback item 2
requires.
"""
from __future__ import annotations

from collections import Counter, defaultdict, OrderedDict
from pathlib import Path

import b0_common as c
import b0_tex

INDEX_MD = c.B0 / "FINAL_EVIDENCE_INDEX.md"
SPEC_MD = c.B0 / "MANUSCRIPT_REVISION_SPEC.md"


def load():
    return {
        "claims": c.read_csv_literal(c.B0 / "manuscript_claim_map.csv"),
        "numeric": c.read_csv_literal(c.B0 / "manuscript_numeric_map.csv"),
        "coverage": c.read_yaml(c.SPEC / "mandatory_coverage.yaml"),
        "todos": c.read_yaml(c.SPEC / "todo_closure.yaml"),
        "forbidden": c.read_yaml(c.SPEC / "forbidden_wording.yaml"),
        "tf": c.read_yaml(c.SPEC / "table_figure_disposition.yaml"),
        "manifest": c.read_json(c.B0 / "FINAL_EVIDENCE_MANIFEST.json"),
        "cov_summary": c.read_json(c.COVERAGE / "coverage_summary.json"),
        "cert": c.read_json(c.CERT / "certification.json"),
    }


# --------------------------------------------------------------------------
def build_index(d: dict, tex: b0_tex.Tex) -> str:
    L, A = [], None
    A = L.append
    cov = d["cov_summary"]
    man = d["manifest"]
    cert = d["cert"]

    A("# Final evidence index")
    A("")
    A("What frozen evidence exists, what it supports, and what it does not. "
      "Generated by `code/b0_6_build_documents.py`; do not edit by hand.")
    A("")
    A("Pinned to `paper/paper_v17_option1.tex` at integration HEAD "
      f"`{cert['integration']['head'][:12]}`, sha256 `{tex.sha256[:32]}...`. "
      "**Line numbers are baseline coordinates only** and go stale as soon as "
      "the writing pass begins; every row of the maps therefore also carries a "
      "`latex_label`, a `source_anchor` (the nearest preceding `\\label`), a "
      "`manuscript_section`, and a normalized baseline excerpt with its sha256, "
      "so the intended passage can be re-identified after earlier edits shift "
      "the lines.")
    A("")

    A("## What this rests on")
    A("")
    A("| | |")
    A("|---|---|")
    p0 = cert["primary_certification"]["p0"]
    p1 = cert["primary_certification"]["p1"]
    A(f"| P0 certification | **{p0['final_tag_certification']}** at tag "
      f"`{c.P0_TAG}`, subtree byte-identical at HEAD |")
    A(f"| P1 certification | **{p1['final_certification']}** at tag "
      f"`{c.P1_TAG}`, subtree byte-identical at HEAD |")
    A(f"| artifacts indexed | {man['counts']['total']} "
      f"({man['counts']['present']} present, "
      f"{man['counts']['absent_legacy']} absent legacy, hashes quoted) |")
    A(f"| numeric map | {cov['numeric_map_rows']} rows, "
      f"{cov['distinct_claim_ids']} distinct scientific values |")
    A(f"| claims | {len(d['claims'])} |")
    A(f"| active numeric tokens | {cov['active_tokens']} "
      f"({cov['active_distinct_tokens']} distinct) |")
    r = cov["active_resolution"]
    A(f"| coverage | {r.get('SOURCED', 0)} sourced, "
      f"{r.get('ALLOWLISTED', 0)} allowlisted, "
      f"{r.get('FLAGGED_UNSUPPORTED', 0)} flagged unsupported |")
    A("")
    A("> **No Tier-B0 output claims CSV bit-exactness.** P1 records that the "
      "committed CSVs round-trip float64 to about 3.55e-15, so every value here "
      "is carried as the literal decimal text found in the artifact and "
      "converted with `decimal.Decimal`, never through float.")
    A("")

    A("## The four render buckets")
    A("")
    A("Tier A neutralised the revision macros in the preamble without editing a "
      "single call site, so what prints is decided by macro identity and by two "
      "kinds of inert region. Getting this wrong is how superseded numbers come "
      "back.")
    A("")
    A("| bucket | mechanism | prints? |")
    A("|---|---|---|")
    A("| `ACTIVE` | plain prose, `\\newtext`, `\\latesttext`, "
      "`\\advisorchange`, `\\textcolor{impGreen}`, `{\\color{latestPurple}}` | yes |")
    A("| `SUPPRESSED` | `\\oldtext{...}`, `oldrevisionblock` | no |")
    A("| `COMMENTED` | after an unescaped `%` | no |")
    A("| `IFFALSE` | inside `\\iffalse ... \\fi` | not even compiled |")
    A("")
    cen = tex.census()
    A("Census, reproduced by `code/b0_tex.py` and checked against the table "
      "`markup_preflight.py` already committed in "
      "`paper_analysis/paper_v17/superseded_text_archive.md`:")
    A("")
    A("| macro | active | inert | total |")
    A("|---|---:|---:|---:|")
    for k in sorted(cen):
        v = cen[k]
        A(f"| `{k}` | {v['active']} | {v['inert']} | {v['total']} |")
    A("")
    A(f"`\\iffalse` regions: "
      f"{', '.join(f'lines {a}-{b}' for a, b in tex.iffalse_regions)}. "
      "**Every ATTOM number lives inside them.** "
      f"There are {len(tex.todos)} `\\todo` sites, all silenced by "
      "`todonotes[disable]`; see the closure table in "
      "`MANUSCRIPT_REVISION_SPEC.md`.")
    A("")

    A("## By manuscript section")
    A("")
    by_sec = OrderedDict()
    for row in sorted(d["claims"], key=lambda r: int(r["baseline_line"])):
        by_sec.setdefault(row["manuscript_section"], []).append(row)
    num_by_anchor = defaultdict(list)
    for row in d["numeric"]:
        num_by_anchor[row["source_anchor"]].append(row)

    for sec, claims in by_sec.items():
        A(f"### {sec}")
        A("")
        A("| claim | disposition | primary / sensitivity | reference cell · purpose | evidence |")
        A("|---|---|---|---|---|")
        for cl in claims:
            arts = [a for a in cl["supporting_artifacts"].split(";")
                    if a and a != "NONE_REQUIRED"]
            ev = ", ".join(f"`{Path(a).name}`" for a in arts) or "*none required*"
            rc = cl["reference_cell"]
            purpose = cl["comparison_purpose"]
            A(f"| `{cl['claim_id']}` (L{cl['baseline_line']}) | "
              f"**{cl['disposition']}** | {cl['primary_or_sensitivity']} | "
              f"{rc} · {purpose} | {ev} |")
        A("")
        for cl in claims:
            A(f"**`{cl['claim_id']}`** — {cl['claim_text']}")
            A("")
            A(f"- *reason:* {cl['reason']}")
            A(f"- *required final message:* {cl['required_final_message']}")
            if cl["forbidden_wording"]:
                A("- *must NOT be used:* "
                  + ", ".join(f"“{x}”" for x in cl["forbidden_wording"].split(";")))
            if cl["numeric_claim_ids"]:
                ids = cl["numeric_claim_ids"].split(";")
                A(f"- *numeric values:* {len(ids)} row(s) in the numeric map, "
                  f"e.g. `{ids[0]}`")
            if cl["counting_unit"] != "NOT_APPLICABLE":
                A(f"- *counting unit:* `{cl['counting_unit']}`")
            if cl["guidance_status"] != "NOT_APPLICABLE":
                A(f"- *guidance status:* `{cl['guidance_status']}`")
            if cl["option2_precedent"]:
                A(f"- *Option-2 wording precedent:* {cl['option2_precedent']}")
            A(f"- *anchor:* `{cl['source_anchor']}` · bucket "
              f"`{cl['render_bucket']}` · priority {cl['priority']} · "
              f"confidence {cl['confidence']}")
            A("")

    A("## Evidence-domain appendix")
    A("")
    A("The mandated coverage topics, one for one. Each must map to at least one "
      "claim; `tests/test_b0_claim_map.py` fails if any is unmapped.")
    A("")
    mapped = defaultdict(list)
    for cl in d["claims"]:
        for t in cl["coverage_topics"].split(";"):
            if t:
                mapped[t].append(cl["claim_id"])
    for topic in d["coverage"]["topics"]:
        ids = mapped.get(topic["topic_id"], [])
        A(f"### `{topic['topic_id']}` — {topic['title']}")
        A("")
        A(" ".join(str(topic["requirement"]).split()))
        A("")
        A(f"Claims: {', '.join('`' + i + '`' for i in ids)}")
        A("")

    A("## Out of scope, recorded")
    A("")
    A("- **External benchmark** — `analysis/external_jurisdiction_benchmark_v1/`, "
      "`berry_attom_validation_v2` / `v3`, `berry_cmf_validation` are "
      "`OUT_OF_SCOPE_FOR_B0`. **No external-benchmark artifact enters "
      "`FINAL_EVIDENCE_MANIFEST.json`**; the exclusions are recorded under "
      "`excluded_streams`, including the one such path that appears in P0's own "
      "`PREFLIGHT.input_artifact_hashes`. Appendix H's active boundary claim is "
      "indexed `KEEP`. The audit looked for active manuscript numbers depending "
      "on that stream and found none: every ATTOM number sits inside an "
      "`\\iffalse` region.")
    A("- **Option 2** — `paper_v17_option2.tex` is read for **wording precedent "
      "only**. No number, threshold, empirical result or scientific conclusion "
      "may be imported from it unless independently supported by the frozen "
      "Tier-B0 maps. No independent Option-2 scientific inventory was performed.")
    A("- **Legacy V6/V12 prediction trees and the CCAO parquet** — gitignored by "
      "design and in no checkout. Indexed with "
      "`present_in_worktree: false` and hashes **quoted** from the frozen index "
      "named in `hash_source`, never re-derived. Tier B0 never reads them; the "
      "read guard in `code/b0_common.py` raises on any path under `output/` or "
      "`data/`, both of which exist in this worktree holding unrelated material.")
    A("")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------
def build_spec(d: dict, tex: b0_tex.Tex) -> str:
    L = []
    A = L.append
    fw = d["forbidden"]

    A("# Manuscript revision specification")
    A("")
    A("What to change in `paper/paper_v17_option1.tex`, why, on what evidence, "
      "and what wording is forbidden. Generated by "
      "`code/b0_6_build_documents.py`; do not edit by hand.")
    A("")
    A("**Tier B0 wrote no replacement manuscript prose and edited no file under "
      "`paper/`.** This document specifies the edits; the writing pass makes "
      "them.")
    A("")
    A("Line numbers are **baseline coordinates only**. Re-identify each passage "
      "by its `latex_label` / `source_anchor` and its normalized baseline "
      "excerpt (with sha256) in `manuscript_claim_map.csv`.")
    A("")

    A("## 0. Reference-cell semantics — the rule that governs the two path tables")
    A("")
    A("A and C are **two frozen roles, not a substitution**. This is the single "
      "most consequential item in this document, and the fix is *not* to replace "
      "A with C.")
    A("")
    A("| cell | forward display name | frozen role | comparison purpose |")
    A("|---|---|---|---|")
    for cid in ("A", "B", "C"):
        r = fw["reference_roles"][cid]
        A(f"| **{cid}** | {r['forward_display_name']} | {r['role']} | "
          f"`{r['comparison_purpose']}` |")
    A("")
    A("The frozen attribution rules, quoted:")
    A("")
    for cid in ("A", "C"):
        r = fw["reference_roles"][cid]
        A(f"- **{cid}** — {' '.join(str(r['attribution_rule']).split())}")
    A("")
    A("Legacy Stage-1 label strings (`Parity-aligned native L2` for B, "
      "`Custom rho=0 origin` for C) may appear **only as values inside Stage-1 "
      "tables**, never as manuscript-facing display names.")
    A("")

    A("### 0.1 Mandatory table highlighting and labelling convention")
    A("")
    A("`tab:path_anchor_summary`, `tab:path_anchor_complementary`, "
      "`tab:ccao_baseline_results` and `tab:ccao_baseline_complementary` "
      "currently bold and star every penalized row against **Cell A alone**. "
      "The paper's own §5.1 caveat says native-to-penalized contrasts are "
      "confounded, and the frozen convention makes Cell C the only "
      "penalty-isolating reference. So the present highlighting reads as a "
      "penalty effect while resting on a workflow-benchmark comparison.")
    A("")
    A("Required in the final tables:")
    A("")
    A("1. **Keep** the A-referenced comparison. It is the assessor-facing "
      "workflow-benchmark question — *could a practitioner do better than the "
      "standard pipeline?* — and it is legitimately reportable, descriptively.")
    A("2. **Add** the C-referenced comparison and mark it as the **primary** "
      "one. It is the penalty-isolating question — *what does rho itself do?*")
    A("3. Use **two visibly different devices**, and never one device for both. "
      "A workable split: boldface for the workflow-benchmark comparison against "
      "Ordinary LightGBM, and a separate marked column, panel or superscript for "
      "the penalty-isolating comparison against the custom-objective rho=0 "
      "origin.")
    A("4. Say which is which **in the notes**, in words, naming both reference "
      "cells by their forward display names.")
    A("5. State, in the notes, that boldface and asterisks denote direction of "
      "movement only — never statistical significance, formal compliance, or "
      "model selection.")
    A("6. Never present an A-referenced difference as a pure penalty effect, and "
      "never label Cell C a workflow benchmark.")
    A("")
    A("A row-level guard enforces the machine-readable half of this: no map row "
      "may carry `reference_cell=A` together with "
      "`comparison_purpose=PENALTY_ISOLATING`, and none may carry "
      "`reference_cell=C` with `comparison_purpose=WORKFLOW_BENCHMARK`.")
    A("")

    A("## 1. Items by priority")
    A("")
    order = {"P0": 0, "P1": 1, "optional cleanup": 2}
    claims = sorted(d["claims"],
                    key=lambda r: (order.get(r["priority"], 9),
                                   int(r["baseline_line"])))
    for pri in ("P0", "P1", "optional cleanup"):
        sub = [x for x in claims if x["priority"] == pri]
        if not sub:
            continue
        A(f"### Priority {pri} ({len(sub)} items)")
        A("")
        for cl in sub:
            A(f"#### `{cl['claim_id']}` — {cl['disposition']}")
            A("")
            A(f"- **where** — {cl['manuscript_section']}, baseline L"
              f"{cl['baseline_line']}, anchor `{cl['source_anchor']}`"
              + (f", label `{cl['latex_label']}`" if cl["latex_label"] else "")
              + f", render bucket `{cl['render_bucket']}`")
            A(f"- **baseline excerpt** — `{cl['baseline_excerpt_norm'][:110]}` "
              f"(sha256 `{cl['baseline_excerpt_sha256'][:16]}...`)")
            A(f"- **current claim** — {cl['claim_text']}")
            why_label = ("why this is correct as it stands"
                         if cl["disposition"] == "KEEP" else
                         "why this is missing" if cl["disposition"] == "ADD" else
                         "why this is a problem")
            A(f"- **{why_label}** — {cl['reason']}")
            A(f"- **required final message** — {cl['required_final_message']}")
            arts = [a for a in cl["supporting_artifacts"].split(";")
                    if a and a != "NONE_REQUIRED"]
            A("- **evidence** — "
              + (", ".join(f"`{a}`" for a in arts) if arts
                 else "*none required (editorial or wording constraint)*"))
            if cl["numeric_claim_ids"]:
                A(f"- **numbers** — `{cl['numeric_claim_ids']}`")
            if cl["forbidden_wording"]:
                A("- **wording that must NOT be used** — "
                  + ", ".join(f"“{x}”" for x in cl["forbidden_wording"].split(";")))
            if cl["counting_unit"] != "NOT_APPLICABLE":
                A(f"- **counting unit** — `{cl['counting_unit']}` (required for "
                  "every aggregate/count statement)")
            if cl["reference_cell"] != "NONE":
                A(f"- **reference cell / purpose** — {cl['reference_cell']} · "
                  f"`{cl['comparison_purpose']}`")
            if cl["option2_precedent"]:
                A(f"- **Option-2 precedent** — {cl['option2_precedent']}")
            A(f"- **confidence** — {cl['confidence']}")
            A("")

    A("## 2. TODO closure — all 19 sites")
    A("")
    A("Tier A silenced `todonotes`, so none of these print. P0 and P1 have "
      "closed most of them; one is closed with a finding that **contradicts** "
      "the surrounding prose.")
    A("")
    A("| # | L | bucket | status | summary |")
    A("|---:|---:|---|---|---|")
    for t in d["todos"]["todos"]:
        A(f"| {t['todo_id']} | {t['baseline_line']} | `{t['render_bucket']}` | "
          f"**{t['closure_status']}** | {' '.join(str(t['summary']).split())} |")
    A("")
    for t in d["todos"]["todos"]:
        A(f"**#{t['todo_id']} (L{t['baseline_line']}) — "
          f"{t['closure_status']}.** {' '.join(str(t['detail']).split())}")
        for e in t.get("frozen_evidence", []) or []:
            A(f"  - `{e}`")
        A("")

    A("## 3. Literature and novelty boundary")
    A("")
    A("Two bibliography gaps, both of which make real content invisible:")
    A("")
    A("1. **Uncited residual-correction literature.** The entries the central "
      "claim rests on are present in the bibliography but never `\\cite`d, so "
      "they do not print. Cite them explicitly in Related Work.")
    A("2. **Uncitable historical entries.** `paper_v17_option1.tex:30-31` loads "
      "only `references.bib` and `references_additions.bib`. The four historical "
      "entries — `PaglinFogarty1972`, `Cheng1974`, `Edelstein1979`, "
      "`SundermanEtAl1990` — live in "
      "`paper/references_major_revision_additions.txt`, which no "
      "`\\addbibresource` loads, so `\\cite` of any of them prints nothing. "
      "**The fix: add a third `\\addbibresource`, then actually cite them.**")
    A("")
    A("Validated, ready-to-paste BibTeX is staged in "
      "`bib/staged_historical_entries.bib`, with per-field provenance in "
      "`bib/STAGED_BIB_PROVENANCE.md`. Three of the four verify field by field "
      "against cached authoritative Crossref responses. `Cheng1974` does not: a "
      "bibliographic query returned no matching record, so every field rests on "
      "the in-repo transcription and is marked `UNVERIFIED_FLAGGED`, and **no "
      "DOI is supplied** because none was found and none may be invented. "
      "`Edelstein1979`'s page range is flagged too: Crossref confirms the start "
      "page 753 but not the end page 768.")
    A("")
    A("Preserve the five non-novelty statements and the eight "
      "defensible-contribution items. " + " ".join(str(fw["option2_rule"]).split()))
    A("")

    A("## 4. Document integrity")
    A("")
    A("- **§5.6 over-suppression.** An `oldrevisionblock` at lines 2898-2910 "
      "wraps both superseded `\\oldtext` and **accepted `\\latesttext`** prose. "
      "Tier A redefined that environment to swallow its whole body, so the "
      "accepted prose at 2900, 2903, 2906, 2907 and 2909 no longer prints. Two "
      "anti-overclaim sentences are therefore invisible — that the folds *“do "
      "not identify a stable multi-metric operating point”* and that *“no "
      "materiality threshold is imposed”* — and `tab:transition_summary` and "
      "`tab:transition_regret` now print in the appendix with no prose "
      "interpreting them. **Do not simply unwrap the block:** the suppressed "
      "prose also quotes the span, regret and concordance values this audit "
      "finds unsupported, so unwrapping wholesale would resurrect them. Restore "
      "sentence by sentence, dropping every clause whose numbers are "
      "unresolvable.")
    A("- **Duplicate `\\label{app:attom}`** — ACTIVE at 4316 and again inside "
      "the `\\iffalse` region at 4323. It is an **inert** duplicate, not a live "
      "clash; it disappears when the inert ATTOM appendix is deleted.")
    A("- **Unreferenced image files** — see `TABLE_FIGURE_DISPOSITION.md`. Every "
      "active figure resolves to a file that exists; in the other direction most "
      "of the tracked files under `paper/img/` are referenced nowhere. Inert, "
      "not broken.")
    A("- **Numeric-consistency flags** — Linear `R^2_P = 0.799` printed in both "
      "panels of `tab:ccao_baseline_results`; Direct rho≈10 held-out VEI "
      "`-10.5%` starred though it lies outside the exposure-draft ±10% band; "
      "Surrogate rho≈10 2025 PRB shown as `0.000`, a rounded estimate rather "
      "than an exact zero; baseline COD 21.3-24.7% against the adopted [5,15] "
      "range; the display anchor written `0.0104811` in one place and "
      "`0.0104811313` in another; and the ED2 URL filename saying `Mar2026` "
      "while the printed title says May 2026 — resolved by "
      "`ed2_source_manifest.json`.")
    A("- **Stale cross-reference** — a pointer to a deleted model-selection "
      "section (todo #5). It is in a commented region today, but the underlying "
      "risk is live now that no penalty strength is selected anywhere.")
    A("")

    A("## 5. Forbidden wording")
    A("")
    A("Data-driven from `spec/forbidden_wording.yaml`; "
      "`tests/test_b0_role_guards.py` reads that file rather than holding its "
      "own copy. A phrase may appear in a Tier-B0 output only inside a sentence "
      "that states the prohibition.")
    A("")
    A("| must NOT be written | why |")
    A("|---|---|")
    for p in fw["forbidden_phrases"]:
        A(f"| “{p['phrase']}” | {' '.join(str(p['why']).split())} |")
    A("")
    A("**Never quote these literals.** " + " ".join(
        str(fw["forbidden_literals_why"]).split()))
    A("")
    for lit in fw["forbidden_literals"]:
        A(f"- `{lit}`")
    A("")
    A("**Mutually exclusive count families.** "
      + " ".join(str(fw["mutually_exclusive_why"]).split()))
    A("")
    for s in fw["mutually_exclusive_count_sets"]:
        A(f"- `{s['counting_unit']}`: {', '.join(s['values'])}")
    A("")

    A("## 6. Tables and figures")
    A("")
    tf = Counter(x["disposition"] for x in d["tf"]["floats"])
    A("Full detail in `TABLE_FIGURE_DISPOSITION.md`. Summary: "
      + ", ".join(f"**{v}** {k}" for k, v in sorted(tf.items())) + ".")
    A("")
    A("| label | bucket | disposition | numbers |")
    A("|---|---|---|---|")
    for x in d["tf"]["floats"]:
        A(f"| `{x['label']}` | `{x['render_bucket']}` | "
          f"**{x['disposition']}** | {x['numbers_fully_supported']} |")
    A("")

    A("## 7. Recommended order for the writing pass")
    A("")
    for i, step in enumerate([
        "Read §0 of this document. The reference-cell semantics govern the two "
        "path tables and the two baseline tables, and getting them wrong "
        "invalidates the rest of the pass.",
        "Delete what cannot be supported: `tab:rho_candidate_regions`, "
        "`tab:transition_summary`, `tab:transition_regret`, the three "
        "event-location figures and `fig:ratio_shape_cv_transition_span_only`, "
        "and the inert `\\iffalse` ATTOM material. Doing this first stops later "
        "edits from being written against numbers that are about to go.",
        "Rebuild `tab:path_anchor_summary` and `tab:path_anchor_complementary` "
        "from the frozen artifacts, applying the §0.1 highlighting convention. "
        "Keep PRB and VEI at all five anchors.",
        "Fix the two baseline tables: re-source the Cell-A columns, re-derive or "
        "remove the Linear columns.",
        "Repair §5.6 sentence by sentence, restoring the anti-overclaim prose "
        "without resurrecting the deleted numbers.",
        "Replace the closed `\\todo` promises with their findings — especially "
        "#16, whose parity audit resolves in the negative, and #13 and #17, "
        "which are closed outright.",
        "Add the missing frozen evidence: the A/B/C reference convention, "
        "matched-beta, the centered-spread comparator, temporal robustness, VEI "
        "ED2 with its counting unit, and smearing as sensitivity.",
        "Fix the bibliography: add the third `\\addbibresource`, paste the "
        "staged entries, resolve the `UNVERIFIED_FLAGGED` fields, and cite the "
        "residual-correction literature.",
        "Update the limitations section with the frozen limitations listed under "
        "`C-discussion-002`.",
        "Do the optional-cleanup items last: the introduction redundancies, the "
        "stale cross-reference, the inert duplicate label.",
    ], 1):
        A(f"{i}. {step}")
    A("")
    return "\n".join(L) + "\n"


def main() -> int:
    tex = b0_tex.Tex()
    d = load()
    c.write_text(INDEX_MD, build_index(d, tex))
    c.write_text(SPEC_MD, build_spec(d, tex))
    for p in (INDEX_MD, SPEC_MD):
        print(f"wrote {c.rel(p)}  ({p.stat().st_size:,} bytes, "
              f"{p.read_text(encoding='utf-8').count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
