"""Write the immutable Section-2 LightGBM freeze for paper-v6 preselection.

Does not run baseline search and does not touch output/robust_rolling_origin_cv_v2.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from canonical_experiment import git_state, lgbm_params_hash, package_versions, write_json
from run_temporal_cv import _build_lgbm_params_from_files

ROOT = REPO / "output" / "paper_v6_preselection"
V2_FREEZE = REPO / "output" / "robust_rolling_origin_cv_v2" / "frozen_baseline.json"
SECTION2_MANIFEST = REPO / "output" / "paper_baseline_2024_2025" / "experiment_manifest.json"
SECTION2_TABLE = REPO / "output" / "paper_baseline_2024_2025" / "table2_metrics_unrounded.csv"
MODEL_PARAMS = REPO / "model_params.yaml"
PARAMS = REPO / "params.yaml"
BEST_CONFIGS = REPO / "best_lgbm_baseline_configs.yaml"


def _sha256(path: Path) -> str:
    if not path.is_file():
        return ""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    (ROOT / "logs").mkdir(exist_ok=True)
    (ROOT / "smoke").mkdir(exist_ok=True)
    (ROOT / "baseline_reporting").mkdir(exist_ok=True)
    (ROOT / "paper_outputs" / "tables").mkdir(parents=True, exist_ok=True)
    (ROOT / "paper_outputs" / "figures").mkdir(exist_ok=True)
    (ROOT / "paper_outputs" / "sources").mkdir(exist_ok=True)
    (REPO / "paper" / "img" / "generated_v6_preselection").mkdir(parents=True, exist_ok=True)

    with MODEL_PARAMS.open("r", encoding="utf-8") as f:
        model_params = yaml.safe_load(f)
    with PARAMS.open("r", encoding="utf-8") as f:
        ccao_params = yaml.safe_load(f)
    lgbm_params = _build_lgbm_params_from_files(
        model_params=model_params,
        ccao_params=ccao_params,
        seed=2025,
        use_ccao_fallback=False,
    )
    param_hash = lgbm_params_hash(lgbm_params)
    config_id = None
    if BEST_CONFIGS.is_file():
        with BEST_CONFIGS.open("r", encoding="utf-8") as f:
            best = yaml.safe_load(f) or {}
        for _name, rec in (best.get("lgbm_baselines") or {}).items():
            rec_params = dict(rec.get("lgbm_params") or {})
            if int(rec_params.get("n_estimators", -1)) == int(lgbm_params.get("n_estimators", 0)):
                if abs(float(rec_params.get("learning_rate", 0.0)) - float(lgbm_params.get("learning_rate", 0.0))) < 1e-12:
                    config_id = rec.get("lgbm_base_config_id") or rec.get("config_id")
                    break

    search_winner_id = None
    search_n_estimators = None
    if V2_FREEZE.is_file():
        v2 = json.loads(V2_FREEZE.read_text(encoding="utf-8"))
        v2_params = dict(v2.get("best_lgbm_params") or {})
        search_n_estimators = v2_params.get("n_estimators")
        search_winner_id = (v2.get("provenance") or {}).get("search_best_config_id")

    payload = {
        "source": "section2_manuscript",
        "search_criterion": "none_section2_manuscript_freeze",
        "config_id": config_id,
        "lgbm_params": lgbm_params,
        "lgbm_params_sha256": param_hash,
        "differs_from_seven_fold_search_winner_407d47775760c14d": True,
        "seven_fold_search_winner": {
            "config_id": search_winner_id,
            "n_estimators": search_n_estimators,
            "freeze_path": str(V2_FREEZE) if V2_FREEZE.is_file() else None,
            "preserved": True,
            "not_used_for_this_experiment": True,
        },
        "provenance": {
            "generation_script": "scripts/run_paper_baseline.py",
            "parameter_source": "model_params.yaml via run_temporal_cv._build_lgbm_params_from_files",
            "section2_experiment_manifest": str(SECTION2_MANIFEST) if SECTION2_MANIFEST.is_file() else None,
            "section2_metrics_csv": str(SECTION2_TABLE) if SECTION2_TABLE.is_file() else None,
            "section2_manifest_sha256": _sha256(SECTION2_MANIFEST),
            "section2_table_sha256": _sha256(SECTION2_TABLE),
            "model_params_yaml": str(MODEL_PARAMS),
            "identification": (
                "Section 2 table/figure artifacts in output/paper_baseline_2024_2025 "
                "were generated by scripts/run_paper_baseline.py using this 500-tree "
                "model_params.yaml vector. Metrics in table2_metrics_unrounded.csv "
                "match the current paper_v6.tex Section 2 display values. This is not "
                "the later seven-fold baseline-search winner (994 trees / 407d47775760c14d)."
            ),
        },
        "data_split_identity": {
            "training_parquet": "data/CCAO/2025/training_data.parquet",
            "development_end": "2023-11-09",
            "heldout": "newest 10% of 2016-2024 eligible sales",
            "forward_year": 2025,
        },
        "versions": package_versions(),
        **git_state(),
    }
    config_path = ROOT / "section2_lgbm_config.json"
    freeze_path = ROOT / "frozen_baseline.json"
    write_json(config_path, payload)
    write_json(
        freeze_path,
        {
            "best_lgbm_params": lgbm_params,
            "source": "section2_manuscript",
            "search_criterion": "none_section2_manuscript_freeze",
            "n_folds_protocol": "paper_v6_seven_fold_expanding_15mo",
            "seed": 2025,
            "lgbm_params_sha256": param_hash,
            "section2_lgbm_config_json": str(config_path),
            "config_id": config_id,
            "versions": package_versions(),
            **git_state(),
        },
    )
    write_json(
        ROOT / "experiment_manifest.json",
        {
            "experiment": "paper_v6_preselection",
            "selection_performed": False,
            "canonical_grid": {
                "LinearRegression": 1,
                "LGBMRegressor": 1,
                "LGBCovPenalty": 51,
                "LGBSmoothPenalty": 51,
                "total_configs": 104,
                "folds": 7,
                "expected_cv_fits": 728,
                "ratio_mode": "diff",
                "identity_surrogate": True,
                "include_cvar": False,
                "include_logistic_proxy": False,
            },
            "section2_lgbm_config_json": str(config_path),
            "frozen_baseline_json": str(freeze_path),
            "lgbm_params_sha256": param_hash,
            "seven_fold_search_namespace_preserved": str(V2_FREEZE.parent),
        },
    )
    print(f"wrote {config_path}")
    print(f"wrote {freeze_path}")
    print(f"n_estimators={lgbm_params.get('n_estimators')} hash={param_hash}")
    print(f"search_winner_id={search_winner_id} n_estimators={search_n_estimators}")


if __name__ == "__main__":
    main()
